### ISSUE TITLE
Missing html content, with online status

### ISSUE THREAD

**Issue by 0object** [mrparkerlol/aos-server-status#1]
Hi, my problem is missing the contents of the html page, when added script. This only when the server is online.  [Example](http://bomb.ga/monitoring/server_status.php)
```
<div>Test visible</div>
  <?php
    include './server_status.php';
    ?>
<div>Test invisible</div>
```
Thanks!

**Comment by mrparkerlol** [comment]
I pushed a change which should fix the issue.

The issue lied where I used exit() rather than a break statement.

Please try again.

**Comment by 0object** [comment]
Many thanks for fix. And thanks for script :) Unfortunately now there are not enough servers. Although the game is amazing.
